@host = http://localhost:8083




//测试，获取所有用户信息
### GET
GET {{host}}/ HTTP/1.1

//注册
### GET
GET {{host}}/users/reg HTTP/1.1
    ?user_phone=18487315405
    &user_code=12345
    &user_name=沐雙惜
    &user_sex=男

//登录
### GET
GET {{host}}/users/login HTTP/1.1
    ?user_phone=18487315405
    &user_code=123456


### POST
POST {{host}}/reg HTTP/1.1
content-type: application/json

{
    "user_phone": "18487315405",
    "user_code": "123456"
}
